### ISSUE TITLE
Duplicate field names when registering instances

### ISSUE THREAD

**Issue by yorban** [JasperFx/lamar#105] opened 2018-11-22 11:36 UTC
Hi,

If I try to register to instances of different types with same type names but from different namespaces, I get an ambiguity issue. For instance, this is a sample registry:
```
class LamarServiceRegistry : ServiceRegistry
    {
        public LamarServiceRegistry()
        {
            var duplicateNameClass1 = new LamarTest1.DuplicateNameClass();
            var duplicateNameClass2 = new LamarTest2.DuplicateNameClass();
            For<Class1>().Use<Class1>();
            For<Class2>().Use<Class2>();
            For<LamarTest1.IDuplicateNameClass>().Use(duplicateNameClass1);
            For<LamarTest2.IDuplicateNameClass>().Use(duplicateNameClass2);
        }
    }
```

Due to the use of the instances duplicateNameClass1 and duplicateNameClass2, the generated file has the following:
```
public class LamarTest_Class1_class1 : Lamar.IoC.Resolvers.TransientResolver<object>
    {
        private readonly LamarTest.LamarTest2.IDuplicateNameClass _duplicateNameClass;
        private readonly System.Func<LamarTest.LamarTest2.IDuplicateNameClass, object> _func_of_IDuplicateNameClass_object;
        private readonly LamarTest.LamarTest1.IDuplicateNameClass _duplicateNameClass;
        private readonly System.Func<object, LamarTest.LamarTest1.IDuplicateNameClass, object> _func_of_object_IDuplicateNameClass_object;

[...]
```

As you can see, the field "_duplicateNameClass" appears twice, yielding an error:

> CS0100: The parameter name 'duplicateNameClass' is a duplicate
CS0102: The type 'LamarTest_Class1_class1' already contains a definition for '_duplicateNameClass'
CS0229: Ambiguity between 'LamarTest_Class1_class1._duplicateNameClass' and 'LamarTest_Class1_class1._duplicateNameClass'
CS0229: Ambiguity between 'IDuplicateNameClass' and 'IDuplicateNameClass'
CS0229: Ambiguity between 'LamarTest_Class1_class1._duplicateNameClass' and 'LamarTest_Class1_class1._duplicateNameClass'
CS0229: Ambiguity between 'IDuplicateNameClass' and 'IDuplicateNameClass'
CS0229: Ambiguity between 'LamarTest_Class1_class1._duplicateNameClass' and 'LamarTest_Class1_class1._duplicateNameClass'
CS0229: Ambiguity between 'LamarTest_Class1_class1._duplicateNameClass' and 'LamarTest_Class1_class1._duplicateNameClass'

So not including the namespace (or otherwise ensuring uniqueness) when generating the field names from the types are problematic.

I've attached a test project to show the issue here: [LamarTest.zip](https://github.com/JasperFx/lamar/files/2607853/LamarTest.zip)

Best,
Mathias

**Comment by jeremydmiller** [comment] 2018-11-24 01:06
@yorban Thanks for the repro steps here, but I think I'm going to say this is a duplicate of https://github.com/JasperFx/lamar/issues/92 that is fixed in master, and will appear shortly in the 2.0 release next week. Regardless of name and how it got there, Lamar now disambiguates duplicated variable names right before compilation by suffixing numbers.

**Closed as completed** 2018-11-24 01:18 UTC
Labels: bug, duplicate
