### ISSUE TITLE
StructureMap to Lamer Error

### ISSUE THREAD

**Issue by Velocity540** [JasperFx/lamar#143] opened 2019-04-02 19:53 UTC
Converted an existing AspNet Core (running on .Net Framework 4.6).

Getting this error
Lamar.IoC.LamarMissingRegistrationException: No service registrations exist or can be derived for Microsoft.Extensions.Logging.ILogger<Microsoft.AspNetCore.Hosting.Internal.WebHost>

We are using serilog, and all was working well with Structuremap.

So far all other projects, except the website have converted very nicely.

**Comment by Velocity540** [comment] 2019-04-03 11:49
Seems I was able to get past that issue, now onto the next.  This one is odd, and I am trying to narrow it down.  Previously worked with Structuremap for years.
Removed SM and replaced with Lamar.

Seems the IHostingEnviornment is getting changed, for no reason.. Very confusing.
 if I  put a breakpoint here, all is well.. The "env" variable is filled in with the correct values. 

        public Startup(IHostingEnvironment env)
        {
            
        }

By the time this breakpoint gets hit the values are all gone (null) except for enviornment which is "Production" (Above this was "Development")

         public void Configure(IApplicationBuilder app, IHostingEnvironment env)
         {
         }

if I comment out the below lines, the values are populated correctly

            services.Scan(s =>
            {
                s.TheCallingAssembly();
                s.WithDefaultConventions();
            });

I created a new sample project from scratch, and this issue does not present itself. Im at wits end here.

**Comment by Velocity540** [comment] 2019-04-03 15:51
I was able to hack around the issue, (Not really a solution but a hack)


Now, I am getting this issue
Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions])


At this pojnt im going to assume Lamar is NOT a replacement for StructureMap.  After spending 1+ entire day on something that by the looks was "simple" I give up..  I could have converted to AutoFac by now.

If Lamar gets to a stable point I'll reconsider.. Thanks for the efforts.

**Comment by CodingGorilla** [comment] 2019-04-03 15:55
Can you describe what you did to "hack around the issue" and which version of Lamar you're using.  I'm pretty sure others have done migrations from SM and not had this particular problem.  Most of the problems that I am aware of were due to the use of classes marked `internal`, but that should have been fixed in 3.0.

**Comment by Velocity540** [comment] 2019-04-03 16:00
Version 3.0.1

For the IHostingEnviornment issue, we tried this

// Top of class
`          private IHostingEnvironment _env;`

// in Startup the IHostingEnviorment was correct.
```
            public Startup(IHostingEnvironment env)
            {
              //Set up configuration sources.
              var builder = new ConfigurationBuilder().AddJsonFile("appsettings.json", false, true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true, 
              true).AddEnvironmentVariables();

            Configuration = builder.Build();
        }
```

// Then this in ConfigureContainer  UGLY
`       services.AddSingleton<IHostingEnvironment>(provider => _env);`
            

then, the IHostingEnviornment was injected properly

```
       public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory 
       loggerFactory)
        {

```

 Now the problem I am having is also described above.  I am sure people have moved from SM to Lamar, but this is a rather large project.  Perhaps Lamar is not mature enough? Not sure.  we have tried everything we can think of to get it to work

the issue has been tracked down to this

 ```
       services.Scan(_ =>
            {
                _.TheCallingAssembly();
                _.WithDefaultConventions();
                _.AddAllTypesOf<IStartupTask>();
                _.LookForRegistries();
                _.AssembliesAndExecutablesFromApplicationBaseDirectory(assembly => assembly.FullName.StartsWith(ROOT_NAMESPACE));

                _.ExcludeNamespace("StructureMap.Testing.Widget5");

            });
```

If I comment out the "AssembliesAndExecutablesFromApplicationBaseDirectory" then the scan completes and moves into Configure.. If leave that in, then we get the error

> Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
> Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
> Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions])


Lamar seems to have an issue with something in one of our DLL's?? That's our guess.

**Comment by CodingGorilla** [comment] 2019-04-03 16:26
Have you done a `.WhatDoIHave()` and `.WhatDidIScan()` to get some diagnostic information?  Also, are you running the scan directly in the Startup class' `Configure()` method?  I do mine in a method called `ConfigureContainer(ServiceRegistry serviceRegistry)`.  I would venture to guess that, if you're doing it in `Configure()` that is likely the culprit.

**Comment by Velocity540** [comment] 2019-04-03 16:38
Im using ` public void ConfigureContainer(ServiceRegistry services)`

I cannot do a .WhatDoIHave() and .WhatDidIScan() since I cannot get into the `Configure() `method. It errors before coming into that method.

Im not sure what different Lamar is doing then SM. Other then adding Lamar, nothing else has changed.

We are using Serilog for logging, but we have not touched logging in  a while.. I have no clue as to why this switch would cause 

> Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
> Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
> Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions])


Link to LoogerFactoryClass with MS
[](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerfactory?view=aspnetcore-2.2)

Seems both of the constructors are there.

**Comment by CodingGorilla** [comment] 2019-04-03 16:50
The amibiguous constructor exception was brought up in #134 also.  For some reason, I have never run into that issue, and @jeremydmiller has indicated that he has unit tests that run _all_ of the ASP.NET Core setup to test all of these things, so I'm not sure why some people run into this one.  But I wonder if the solution to that is not to exclude it from the scan using: https://jasperfx.github.io/lamar/documentation/ioc/registration/auto-registration-and-conventions/#sec3 .  There shouldn't be any need for the scanner to re-register the base ASP.NET Core items, they should already be in the service collection when lamar takes over.  Do you mind giving that a shot, I'm curious if that solves the problem.

**Comment by Velocity540** [comment] 2019-04-03 17:01
im assuming you mean like this

```
           services.Scan(s =>
            {
                s.TheCallingAssembly();
                s.WithDefaultConventions();
                s.AssembliesAndExecutablesFromApplicationBaseDirectory(assembly => assembly.FullName.StartsWith("MyProj"));

                s.ExcludeNamespace("Microsoft.Extensions.Logging.LoggerFactory");
            });

            services.AddSingleton<IHostingEnvironment>(provider => _env);

```

No luck on that one

**Comment by CodingGorilla** [comment] 2019-04-03 17:08
I was thinking more along the lines of: `s.ExcludeType<Microsoft.Extensions.Logging.LoggerFactory>()`, but it's probably the same effect, just more specific.  Same error though?

**Comment by CodingGorilla** [comment] 2019-04-03 17:11
Also, could you provide a full stack trace for the exception?

**Comment by Velocity540** [comment] 2019-04-03 17:19
Same error..
Lamar must be overriding the base ASP.NET CORE items. I feel like the issues are interrelated. This, and the IHostingEnviorment

StackTrace

>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at WebApplication13.Program.Main(String[] args)

**Comment by CodingGorilla** [comment] 2019-04-03 17:21
Ok, so this is all coming from the built in DI, there is no mention of Lamar in there at all.  Do you have the `.UseLamar()` in your `Program.cs` file?  It should come before `.UseStartup<Startup>()`.

**Comment by Velocity540** [comment] 2019-04-03 17:22
```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseLamar()
                .UseStartup<Startup>();
    }
```

**Comment by CodingGorilla** [comment] 2019-04-03 18:00
And you're saying this exception is thrown before your `Startup.Configure()` method is called?  If that's the case, then I'm completely at a loss, but I don't see how this can be coming from Lamar based on the information that you have provided (namely the stack trace).

**Comment by Velocity540** [comment] 2019-04-03 18:09
Yes, the exception is thrown before `Startup.Configure()`
We are completely at a loss also right now. This fact, coupled with the fact the I had to hack the IHostingEnviornment is probably not a coincidence thought. 

My guess is somehow Lamar is overrideing the default ASP DI somehow? it might not show up on smaller projects or tests

**Comment by CodingGorilla** [comment] 2019-04-03 18:17
I think your suspicions are correct, but I think the real problem here is that Lamar is not actually running.  The whole point of Lamar is to _replace_ the default ASP.Net DI, if it didn't replace it then what would be the point?  *But* the stack trace you provided provides no indication that Lamar is even involved.  If you put a breakpoint in your `Startup.ConfigureServices()` and one in `Startup.ConfigureContainer()`, can you inspect the actual runtime type for the `IServiceCollection` and `ServiceRegistry` respectively.  The `Startup.ConfigureServices()` should run first, and have a parameter of type: `Microsoft.Extensions.DependencyInjection.ServiceCollection`.  Then the `ConfigureContainer` should have a parameter type of: `Lamar.ServiceRegistry`.

Is there any chance you can provide a sample project that reproduces this?

**Comment by Velocity540** [comment] 2019-04-04 01:31
We were able to remove StructureMap and Lamar, we added AutoFac. Small amount of config, the web site was off and running.

I would like to take the time to put together a sample, and see if I can help you with what's going wrong. Give me a day or 2

**Comment by jeremydmiller** [comment] 2019-04-04 02:06
@Velocity540 That's the built in ASP.Net Core DI container that's blowing up in the stacktrace you posted up above, not Lamar

**Comment by jeremydmiller** [comment] 2019-04-04 02:07
@CodingGorilla This one's fun. AspNetCore starts up a couple different IoC containers during bootstrapping to build out things like IHostingEnvironment and IConfiguration. That could be where the exception is happening. I still don't think this is Lamar though

**Comment by CodingGorilla** [comment] 2019-04-04 14:17
@jeremydmiller That's interesting, I didn't know that.  But I agree, based on everything I've seen I can't see how this is caused by Lamar, but at the same time it looks like Lamar **should be** working.  I really hope he gets some time to set up a repro project, I hate unsolved mysteries. 😃

**Comment by Velocity540** [comment] 2019-04-04 14:18
I agree about the unsolved mysteries.. I will get a sample project up and running by tomorrow.

**Comment by moghthalkushal** [comment] 2019-05-11 12:35
I am facing the same issue

System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions])
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)

**Comment by jeremydmiller** [comment] 2019-05-11 12:55
@moghthalkushal Notice how there's absolutely nothing about Lamar in that stacktrace. Lamar isn't active in your app. Your stacktrace is blowing up in the built in DI container.

**Comment by moghthalkushal** [comment] 2019-05-11 13:03
> @moghthalkushal Notice how there's absolutely nothing about Lamar in that stacktrace. Lamar isn't active in your app. Your stacktrace is blowing up in the built in DI container.

oops wrongly pasted , i will send you the detailed trace.

**Comment by moghthalkushal** [comment] 2019-05-11 18:28
> @moghthalkushal Notice how there's absolutely nothing about Lamar in that stacktrace. Lamar isn't active in your app. Your stacktrace is blowing up in the built in DI container.

My bad , it was due to vs , i did a restart everything worked fine , nuget had not restored the packages properly.

**Comment by radufilipescu** [comment] 2019-06-30 14:04
The same exception is trown when i add the following line in Startup.ConfigureContainer method only:

cfg.For(typeof(IRequestHandler<CreateUserCmd, CreateUserCmdResponse>)).DecorateAllWith(typeof(CreateUserCmdHandlerDecorator1));

**Comment by jeremydmiller** [comment] 2019-06-30 14:31
@radufilipescu What "same exception" are you getting? If you're erroring out on the line above, it can't be the same thing. Is there even "Lamar" in your stacktrace?

**Comment by radufilipescu** [comment] 2019-07-01 08:58
Sorry for my late reply. 

The exception is trown in Program Main method:

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
             WebHost.CreateDefaultBuilder(args)
                .UseLamar()
                .UseStartup<Startup>();
    }

By "same exception" i mean the following:

System.InvalidOperationException
HResult=0x80131509
Message=Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions) Void .ctor(System.Collections.Generic.IEnumerable1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor1[Microsoft.Extensions.Logging.LoggerFilterOptions])

**Comment by darman96** [comment] 2019-08-13 10:09
Hello guys,

I think we found what is causing this error today at work.
A coworker of mine thinks that when an error occurs in Lamar or some other DI Container used in an ASP.NetCore Project the build in DI Container tries to create an error Log and to do that it needs a LoggerFactory but if you don't use the build in Logging system you probably haven't set up a LoggerProvider so it crashes.

A quick way to see what the actual error is, would be to create a lamar container at the end of the ConfigureContainer Method which then throws the real exception. Or you could just use the ConfigureServices Method to register a DebugLoggerProvider which allows ASP to log the error.

I hope this helps some of you.

**Comment by jeremydmiller** [comment] 2019-09-15 19:57
I'm really not convinced this is a Lamar error per se, and there's no recent activity

**Closed as completed by jeremydmiller** 2019-09-15 19:57 UTC
Labels: question

**Comment by shivanaru** [comment] 2020-03-27 01:14
I am having similar issue. When I use NSwag or Swagger CLI inside csproj Target to generate TypeScript interfaces from CSharp classes, it gives me this error. 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Lamar.IoC.LamarMissingRegistrationException: No service registrations exist or can be derived for NSwag.Generation.IOpenApiDocumentGenerator
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithDocumentProviderAsync(IServiceProvider serviceProvider) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 286
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 276
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 29
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 170

**Comment by jeremydmiller** [comment] 2020-03-27 02:42
@shivanaru That's not a similar error, and that exception means what it says. There's no registration for `IOpenApiDocumentGenerator`

**Comment by shivanaru** [comment] 2020-03-27 02:59
Thank you for your response! How can I tell Lamar to ignore it?

**Comment by jeremydmiller** [comment] 2020-03-27 03:01
Um, you can't. Can you get something registered for that type? You might ping the NSwag folks.

**Comment by shivanaru** [comment] 2020-03-27 03:45
Okay. Meanwhile I wanted to change it a little bit out and see. Now I get this error. Can you please shed some light on this? (.Net core 3.1, Lamar IoC with ConfigureContainer(ServiceRegistry){}. Also has ConfigureServices, Configure methods in the startup.cs) 

Unhandled exception. System.InvalidOperationException: No service for type 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[Lamar.ServiceRegistry]' has been registered.
9>       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
9>       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
9>       at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
9>       at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
9>       at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
9>       at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
9>       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
9>       at Swashbuckle.AspNetCore.Cli.Program.BuildWebHost(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 142
9>       at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 68
9>       at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
9>       at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
9>       at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 107

**Comment by GhimpuLucianEduard** [comment] 2021-01-25 14:32
Had the same issue discribed by @shivanaru, adding here a solution in case someone faces the same situation.

What solved it for me was adding this class:

```csharp
public class SwaggerHostFactory
{
    public static IHost CreateHost()
    {
        return Program.CreateHostBuilder(new string[0]).Build();
    }
}
```

Here's a link to a related issue of Swashbuckle: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1180
