### ISSUE TITLE
Lamar 3.0.3 fails in multi threaded scenario

### ISSUE THREAD

**Issue by danielpalme** [JasperFx/lamar#157] opened 2019-05-06 19:58 UTC
If a class has a dependency on `IEnumerable<IFoo>` and you register several `IFoo` implementations, Lamar fails in a multi threaded scenario.
You can get different problems:
- NULL is passed in the list of IFoos
- Incorrect number of IFoos is supplied

The problem seems only to occur with version 3.0.3. In previous versions I did not experience the problem.

Here's a sample project to reproduce the issue:
[Sample.zip](https://github.com/JasperFx/lamar/files/3149621/Sample.zip)

**Comment by jeremydmiller** [comment] 2019-05-28 16:14
@danielpalme Sorry this one slipped by me. I'll try to take a look at your sample project in the next couple days

**Comment by jeremydmiller** [comment] 2019-07-03 20:35
Finally looked at this, can reproduce, but out of time. Might be after the 7/4 holiday now. Sorry for the long delay.

**Comment by jeremydmiller** [comment] 2019-07-08 16:48
@danielpalme I have no earthly idea why this happens even after a couple hours of fighting with it. The super easy work around though is to just use arguments of type `ISimpleAdapter[]` or `IReadOnlyList<ISimpleAdapter>` and it works just fine.

I'm going to leave this open, but the real fix is probably just going to be some documentation.

**Comment by CDargis** [comment] 2019-09-10 20:26
Bump. I believe we are seeing this issue with integration with MediatR: https://github.com/jbogard/MediatR/issues/438

> I'm going to leave this open, but the real fix is probably just going to be some documentation.

Can we please try and dig into this one? I don't want to ask @jbogard to update a framework that is DI container agnostic.

**Comment by jbogard** [comment] 2019-09-10 20:28
""""""Agnostic""""""

**Comment by jeremydmiller** [comment] 2019-09-10 20:43
@CDargis I see absolutely nothing there about Lamar in your stacktraces. I'm gonna wait until it plays out on the MediatR issue.

**Comment by CDargis** [comment] 2019-09-10 21:28
@jeremydmiller you aren't going to see any Lamar references in MediatR. Consumers can bring their own containers. This problem happens _after_ Lamar has returned a list of instances. One item in this list is `null` hence the null reference exception seen in the linked issue. Sometimes there are duplicate items.

Does this help move the issue along?
![image](https://user-images.githubusercontent.com/2372977/64651488-40d33380-d3e7-11e9-98ef-24a1281d099a.png)
![image](https://user-images.githubusercontent.com/2372977/64652254-0074b500-d3e9-11e9-9691-5cdbb9002738.png)

```
public interface IClock
{
}

public class Clock : IClock
{
    public void Tick()
    {
    }
}

public class AnotherClock : IClock
{
    public void Tick()
    {
    }
}

class LamarSandbox
{
    public async Task StartAsync()
    {
        Lamar.Container container = new Lamar.Container(x =>
        {
            x.AddTransient<IClock, Clock>();
            x.AddTransient<IClock, AnotherClock>();
        });
        int times = 100000;
        List<Task> tasks = new List<Task>();
        for (int i = 0; i < times; i++)
        {
            Task t = new Task(() => Resolve(container));
            t.Start();
            tasks.Add(t);
        }
        await Task.WhenAll(tasks);
    }

    private void Resolve(Lamar.Container container)
    {
        IEnumerable<IClock> clocks = container.GetInstance<IEnumerable<IClock>>();
        if(clocks.Contains(null))
        {
            Console.Write("null!!");
        }
    }
}
```

**Comment by CDargis** [comment] 2019-09-10 21:40
FWIW, I can reproduce this issue in every 3.* version. I can't seem to reproduce in 2.1.0

**Comment by CDargis** [comment] 2019-09-10 21:43
FWIW, I can reproduce in Lamar.Microsoft.DependencyInjection 3.0.0, 3.1.0 and 3.1.2. Can't seem to reproduce in 2.1.0.

**Comment by jeremydmiller** [comment] 2019-09-10 22:50
Sigh, okay. MediatR has historically been a huge PITA for me supporting containers and I generally refuse to help support folks who get tangled up in it

Sorry, but I don't have enough bandwidth to fight with this one this week.

**Comment by jeremydmiller** [comment] 2019-09-10 23:27
Do see the workarounds above though please

**Comment by jbogard** [comment] 2019-09-11 00:05
Yeah don’t put this one on me lol I’m trying to keep things simpler by
relying less on exotic features.

**Comment by jeremydmiller** [comment] 2019-09-11 01:08
@jbogard It's not you man, it's the banana pants things that people do with generics trying to shoehorn crazy middleware strategies into MediatR that kills me

**Comment by CDargis** [comment] 2019-09-11 13:47
>Sorry, but I don't have enough bandwidth to fight with this one this week.

I can definitely empathize with lack of bandwidth.

>Do see the workarounds above though please

I can't directly use those workarounds due to the way MediatR consumes containers.

>@jbogard It's not you man, it's the banana pants things that people do with generics trying to shoehorn crazy middleware strategies into MediatR that kills me

You do realize this issue has nothing to do with generics or even MediatR? This is just `container.GetInstance<IEnumerable<T>>` failing in a multi-threaded scenario. I regret mentioning MediatR.

**Comment by jeremydmiller** [comment] 2019-09-11 13:51
@CDargis MediatR **in the past** has been a huge PITA for me, as I've said a couple times. And it **is** related to what you're seeing here because of the way Lamar has to go discover the potential open generics/closed generics handlers inside of MediatR at runtime. The internal locking isn't quite right somehow, and that's the root cause of your issue here.

**Comment by jorhar** [comment] 2019-09-13 15:06
For anyone who stumbles upon this thread experiencing a similar issue....we were unable to come to any  type of resolution and unfortunately had to transition back to [StructureMap](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection). 

As @jeremydmiller described above, there seems to be some issue with how Lamar resolves open generics or collections of open generics under heavy load...or something like that, and MediatR relies on open generic discovery.

At the time of this writing StructureMap has been [sunsetted ](https://jeremydmiller.com/2018/01/29/sunsetting-structuremap/) however. MediatR does include a very helpful [Container Feature Support](https://github.com/jbogard/MediatR/wiki/Container-Feature-Support) page.

**Comment by jeremydmiller** [comment] 2019-09-13 20:03
I HAVE A FIX FOR THIS IN A LOCAL BRANCH!!!!!!!!!

This is finally getting taken care of in Lamar v3.1 out in the next 3-4 days.

**Closed as completed** 2019-09-13 20:05 UTC
